In [1]:
from sqlalchemy import create_engine, inspect
import numpy as np
import pandas as pd
import yaml 
import psycopg2

In [2]:
path = r'C:\Users\Razer\Documents\AI_Core\mrdc\db_creds.yaml'

In [3]:
with open(path, 'r') as file:
    db_creds = yaml.safe_load(file)
print(db_creds)

{'RDS_HOST': 'data-handling-project-readonly.cq2e8zno855e.eu-west-1.rds.amazonaws.com', 'RDS_PASSWORD': 'AiCore2022', 'RDS_USER': 'aicore_admin', 'RDS_DATABASE': 'postgres', 'RDS_PORT': 5432, 'RDS_DATABASE_TYPE': 'postgresql', 'DBAPI': 'psycopg2', 'LOCAL_DATABASE_TYPE': 'postgresql', 'LOCAL_DB_API': 'psycopg2', 'LOCAL_USER': 'postgres', 'LOCAL_PASSWORD': 'password', 'LOCAL_HOST': 'localhost', 'LOCAL_PORT': 5432, 'LOCAL_DATABASE': 'sales_data'}

In [4]:
HOST = db_creds.get('RDS_HOST')
PASSWORD = db_creds.get('RDS_PASSWORD')
USER = db_creds.get('RDS_USER')
DATABASE = db_creds.get('RDS_DATABASE')
PORT = db_creds.get('RDS_PORT')
DBTYPE = db_creds.get('RDS_DATABASE_TYPE')
DBAPI = db_creds.get('DBAPI')

In [5]:
url = f"{DBTYPE}+{DBAPI}://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
url

'postgresql+psycopg2://aicore_admin:AiCore2022@data-handling-project-readonly.cq2e8zno855e.eu-west-1.rds.amazonaws.com:5432/postgres'

In [6]:
engine = create_engine(url)
print(engine)

Engine(postgresql+psycopg2://aicore_admin:***@data-handling-project-readonly.cq2e8zno855e.eu-west-1.rds.amazonaws.com:5432/postgres)

In [7]:
engine.connect()
inspector = inspect(engine)
table_names = inspector.get_table_names()
print(table_names)

['legacy_store_details', 'dim_card_details', 'legacy_users', 'orders_table']

In [8]:
'''
AICore notebook 
from sqlalchemy import inspect
inspector = inspect(engine)
inspector.get_table_names()

actors = pd.read_sql_table('actor', engine)
'''

"\nAICore notebook \nfrom sqlalchemy import inspect\ninspector = inspect(engine)\ninspector.get_table_names()\n\nactors = pd.read_sql_table('actor', engine)\n"

In [9]:
# from sqlalchemy import text
# with engine.connect() as connection:
#     result = connection.execute(text("SELECT * FROM legacy_users"))
#     for row in result:
#         print(row)

In [10]:
users = pd.read_sql_table('legacy_users', engine)
users

,index,first_name,last_name,date_of_birth,company,email_address,address,country,country_code,phone_number,join_date,user_uuid
0,0,Sigfried,Noack,1990-09-30,Heydrich Junitz KG,rudi79@winkler.de,Zimmerstr. 1/0\n59015 Gießen,Germany,DE,+49(0) 047905356,2018-10-10,93caf182-e4e9-4c6e-bebb-60a1a9dcf9b8
1,1,Guy,Allen,1940-12-01,Fox Ltd,rhodesclifford@henderson.com,Studio 22a\nLynne terrace\nMcCarthymouth\nTF0 9GH,United Kingdom,GB,(0161) 496 0674,2001-12-20,8fe96c3a-d62d-4eb5-b313-cf12d9126a49
2,2,Harry,Lawrence,1995-08-02,"Johnson, Jones and Harris",glen98@bryant-marshall.co.uk,92 Ann drive\nJoanborough\nSK0 6LR,United Kingdom,GB,+44(0)121 4960340,2016-12-16,fc461df4-b919-48b2-909e-55c95a03fe6b
3,3,Darren,Hussain,1972-09-23,Wheeler LLC,daniellebryan@thompson.org,19 Robinson meadow\nNew Tracy\nW22 2QG,United Kingdom,GB,(0306) 999 0871,2004-02-23,6104719f-ef14-4b09-bf04-fb0c4620acb0
4,4,Garry,Stone,1952-12-20,Warner Inc,billy14@long-warren.com,3 White pass\nHunterborough\nNN96 4UE,United Kingdom,GB,0121 496 0225,2006-09-01,9523a6d3-b2dd-4670-a51a-36aebc89f579
...,...,...,...,...,...,...,...,...,...,...,...,...
15315,14913,Stephen,Jenkins,1943-08-09,"Thornton, Carroll and Newman",s.jenkins@smith.com,Studio 41I\nJones lodge\nOliviaborough\nE8 3DU,United Kingdom,GB,+44(0)292018946,2016-04-15,2bd3a12f-a92d-4cdd-b99c-fc70572db302
15316,14994,Stephen,Smith,1948-08-20,Robinson-Harris,s.smith@smith.com,530 Young parkway\nMillsfurt\nL4G 7NX,United Kingdom,GB,+44(0)1144960977,2020-07-20,d234c04b-c07c-46a5-a902-526f91478ecc
15317,15012,Stephen,Losekann,1940-10-09,Rosenow,s.losekann@smith.com,Viviane-Fritsch-Straße 3/5\n15064 Bad Liebenwerda,Germany,DE,02984 08192,2021-03-07,1a0a8b7b-7c17-42d8-a946-8a85d5495651
15318,15269,Stephen,Rivera,1952-06-04,"Taylor, Fry and Jones",s.rivera@smith.com,"660 Ross Falls Suite 357\nAnthonymouth, MA 09610",United States,US,239.711.3836,2011-01-03,187fe06e-bd5f-4381-af2f-d7ac37ca7572
15319,1249,Stephen,Duncan,1994-03-27,"Phillips, Brown and Powell",s.duncan@smith.com,Studio 4\nHancock road\nPhillipsview\nST1X 3XB,United Kingdom,GB,+44(0)1314960870,2015-08-28,0589bbca-1d58-4b1f-9d0a-04ed4c57aaa1

In [11]:
users_rd = users.drop_duplicates()
users_rd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15320 entries, 0 to 15319
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          15320 non-null  int64
 1   first_name     15320 non-null  object
 2   last_name      15320 non-null  object
 3   date_of_birth  15320 non-null  object
 4   company        15320 non-null  object
 5   email_address  15320 non-null  object
 6   address        15320 non-null  object
 7   country        15320 non-null  object
 8   country_code   15320 non-null  object
 9   phone_number   15320 non-null  object
 10  join_date      15320 non-null  object
 11  user_uuid      15320 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.4+ MB

In [12]:
def convert_birth_date(users_rd):
    # Apply the conversion logic directly to the 'birth_date' column
    try:
        users_rd['join_date'] = pd.to_datetime(users_rd['join_date'], errors='coerce').dt.strftime('%Y-%m-%d')
    except ValueError:
        users_rd['join_date'] = users_rd['join_date'].apply(lambda x: pd.to_datetime(x, format='%Y %B %d').strftime('%Y-%m-%d'))
    
    return users_rd

In [13]:
users_rd = convert_birth_date(users_rd)

# Print the entry at index 202
print(users_rd['join_date'].iloc[202])

nan

In [14]:
users_rd = convert_birth_date(users_rd)

# Display the DataFrame to verify the results
print(users_rd)

       index first_name last_name date_of_birth                       company  \
0          0   Sigfried     Noack    1990-09-30            Heydrich Junitz KG
1          1        Guy     Allen    1940-12-01                       Fox Ltd
2          2      Harry  Lawrence    1995-08-02     Johnson, Jones and Harris
3          3     Darren   Hussain    1972-09-23                   Wheeler LLC
4          4      Garry     Stone    1952-12-20                    Warner Inc
...      ...        ...       ...           ...                           ...
15315  14913    Stephen   Jenkins    1943-08-09  Thornton, Carroll and Newman
15316  14994    Stephen     Smith    1948-08-20               Robinson-Harris
15317  15012    Stephen  Losekann    1940-10-09                       Rosenow
15318  15269    Stephen    Rivera    1952-06-04         Taylor, Fry and Jones
15319   1249    Stephen    Duncan    1994-03-27    Phillips, Brown and Powell

                      email_address  \
0                 rudi79@winkler.de
1      rhodesclifford@henderson.com
2      glen98@bryant-marshall.co.uk
3        daniellebryan@thompson.org
4           billy14@long-warren.com
...                             ...
15315           s.jenkins@smith.com
15316             s.smith@smith.com
15317          s.losekann@smith.com
15318            s.rivera@smith.com
15319            s.duncan@smith.com

                                                 address         country  \
0                           Zimmerstr. 1/0\n59015 Gießen         Germany
1      Studio 22a\nLynne terrace\nMcCarthymouth\nTF0 9GH  United Kingdom
2                     92 Ann drive\nJoanborough\nSK0 6LR  United Kingdom
3                 19 Robinson meadow\nNew Tracy\nW22 2QG  United Kingdom
4                  3 White pass\nHunterborough\nNN96 4UE  United Kingdom
...                                                  ...             ...
15315     Studio 41I\nJones lodge\nOliviaborough\nE8 3DU  United Kingdom
15316              530 Young parkway\nMillsfurt\nL4G 7NX  United Kingdom
15317  Viviane-Fritsch-Straße 3/5\n15064 Bad Liebenwerda         Germany
15318   660 Ross Falls Suite 357\nAnthonymouth, MA 09610   United States
15319     Studio 4\nHancock road\nPhillipsview\nST1X 3XB  United Kingdom

      country_code       phone_number   join_date  \
0               DE   +49(0) 047905356  2018-10-10
1               GB    (0161) 496 0674  2001-12-20
2               GB  +44(0)121 4960340  2016-12-16
3               GB    (0306) 999 0871  2004-02-23
4               GB      0121 496 0225  2006-09-01
...            ...                ...         ...
15315           GB    +44(0)292018946  2016-04-15
15316           GB   +44(0)1144960977  2020-07-20
15317           DE        02984 08192  2021-03-07
15318           US       239.711.3836  2011-01-03
15319           GB   +44(0)1314960870  2015-08-28

                                  user_uuid
0      93caf182-e4e9-4c6e-bebb-60a1a9dcf9b8
1      8fe96c3a-d62d-4eb5-b313-cf12d9126a49
2      fc461df4-b919-48b2-909e-55c95a03fe6b
3      6104719f-ef14-4b09-bf04-fb0c4620acb0
4      9523a6d3-b2dd-4670-a51a-36aebc89f579
...                                     ...
15315  2bd3a12f-a92d-4cdd-b99c-fc70572db302
15316  d234c04b-c07c-46a5-a902-526f91478ecc
15317  1a0a8b7b-7c17-42d8-a946-8a85d5495651
15318  187fe06e-bd5f-4381-af2f-d7ac37ca7572
15319  0589bbca-1d58-4b1f-9d0a-04ed4c57aaa1

[15320 rows x 12 columns]

In [15]:
row202 = users_rd.iloc[202]
row202

index                                               202
first_name                                      Mohamed
last_name                                      Woodward
date_of_birth                                1968-10-25
company                        Barrett, Jones and Smith
email_address               colemandanny@grant-lamb.org
address          96 Danny trail\nEast Valerie\nKA39 2JN
country                                  United Kingdom
country_code                                         GB
phone_number                              (0113)4960884
join_date                                           NaN
user_uuid          6904f151-6d32-4d1e-b477-41801a9a8e83
Name: 202, dtype: object

In [16]:
# Filter out rows where 'birth_date' is NaN or null
users_rd_cleaned = users_rd.dropna(subset=['join_date'])

In [17]:

def convert_birth_date(users_rd):
    def convert_single_date(date_str):
        try:
            # Attempt standard 'YYYY-MM-DD' format conversion
            return pd.to_datetime(date_str).strftime('%Y-%m-%d')
        except ValueError:
            try:
                # Attempt 'YYYY MONTH DD' format conversion
                return pd.to_datetime(date_str, format='%Y %B %d').strftime('%Y-%m-%d')
            except ValueError:
                # Return the original value if all parsing attempts fail
                return pd.NaT

    # Apply the conversion function to the 'birth_date' column
    users_rd['join_date'] = users_rd['join_date'].apply(convert_single_date)
    
    return users_rd

# Apply the function to your DataFrame
users_rd = convert_birth_date(users_rd)

# Print the entry at index 202
print(f"Entry at index 202: {users_rd['join_date'].iloc[202]}")

Entry at index 202: NaT

In [18]:
# Apply the conversion function to the cleaned DataFrame
users_rd_cleaned = convert_birth_date(users_rd_cleaned)

C:\Users\Razer\AppData\Local\Temp\ipykernel_21980\3640901061.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  users_rd['join_date'] = users_rd['join_date'].apply(convert_single_date)

In [19]:
import re
# Check for NaT/NaN entries after conversion
nan_entries = users_rd_cleaned[users_rd_cleaned['join_date'].isna()]
print(f"Number of NaT/NaN entries after conversion: {len(nan_entries)}")
display(nan_entries)

# Check for invalid format entries after conversion
invalid_entries = users_rd_cleaned[~users_rd_cleaned['join_date'].apply(lambda x: bool(re.match(r'^\d{4}-\d{2}-\d{2}$', str(x))))]
print(f"Number of invalid format entries after conversion: {len(invalid_entries)}")
display(invalid_entries)

Number of NaT/NaN entries after conversion: 0

Empty DataFrame
Columns: [index, first_name, last_name, date_of_birth, company, email_address, address, country, country_code, phone_number, join_date, user_uuid]
Index: []

Number of invalid format entries after conversion: 0

Empty DataFrame
Columns: [index, first_name, last_name, date_of_birth, company, email_address, address, country, country_code, phone_number, join_date, user_uuid]
Index: []

In [20]:
# Check for any NaT (Not a Time) values in the column
nan_entries = users_rd[users_rd['join_date'].isna()]

print(f"Number of NaT/NaN entries: {len(nan_entries)}")
display(nan_entries)

Number of NaT/NaN entries: 59

,index,first_name,last_name,date_of_birth,company,email_address,address,country,country_code,phone_number,join_date,user_uuid
202,202,Mohamed,Woodward,1968-10-25,"Barrett, Jones and Smith",colemandanny@grant-lamb.org,96 Danny trail\nEast Valerie\nKA39 2JN,United Kingdom,GB,(0113)4960884,NaT,6904f151-6d32-4d1e-b477-41801a9a8e83
752,752,PYCLKLLC7I,W350SCUD6R,KBTI7FI7Y3,R7IZUNSQX0,3Q791B3VIY,YW2YXLOQ5J,I7G4DMDZOZ,VSM4IZ4EL3,A4Q4HQBI3I,NaT,W43MSCMQ88
866,867,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
1022,1023,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
1046,1047,GI4C78KWH0,UTB5PPYFG8,OFH8YGZJWN,CA1XGS8GZW,7HSZB429UK,63GXGYR3XL,AJ1ENKS3QL,QVUW9JSKY3,64ZO0ONUQO,NaT,BUE34OU973
1073,1074,Michelle,Young,1963-08-10,"Jones, Simpson and Bates",victoriahughes@lee-hooper.com,757 Ahmed ford\nEast Bethmouth\nM3 7XJ,United Kingdom,GB,+44(0)1632 960 310,NaT,4f3703c0-e020-4d36-93f2-38f077e8467e
1347,1349,Jonathan,Johnson,1952-12-03,"Hall, Thomson and Stevens",adamshugh@evans-gough.com,1 Reece plains\nWest Jayhaven\nN2 5JH,United Kingdom,GB,020 7946 0952,NaT,7508866e-18dd-4530-890b-a7fda09595f0
1569,1571,Mandy,Little,1990-07-23,Jackson and Sons,jamieglover@ingram.com,96 Knowles ports\nVincentfurt\nNP0P 0NB,United Kingdom,GB,0117 4960172,NaT,74a4e9bf-4baf-4f17-bd35-594471d68938
1805,1807,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
2103,2103,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
2437,2439,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
2439,2441,Johannes,Mitschke,2003-06-04,Huhn,apollonia19@hering.net,Klaus-D.-Hellwig-Gasse 118\n13930 Jessen,Germany,DE,+49(0)0887 099768,NaT,a9073341-1fa3-4bcc-982f-5287f4224485
2480,2482,Ashley,Kelly,1941-11-27,James-Marshall,ymorris@buckley.info,Flat 7\nLuke falls\nSouth Brucemouth\nSM4V 9FS,United Kingdom,GB,+44(0)114 496 0729,NaT,a307bb45-6762-4766-a591-f14545f3a9e2
2739,6526,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
2764,2764,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
2995,2997,DPAJNJL6PR,B8ZGN8ZJ84,PQPEUO937L,0YJ2FRMDB4,O5Q6D7FDAF,Y1GY1G3EM5,XGI7FM0VBJ,0CU6LW3NKB,DU9UJ42F3E,NaT,56URKLG01W
3164,3167,Barbara,Daniels,1960-10-30,Kemp Inc,zcole@gill.com,Studio 54\nChloe brook\nWestonshire\nOX9X 9PY,United Kingdom,GB,+44(0)115 496 0250,NaT,d2471fcd-4aae-438f-b0ef-6de2a68ac3ab
3536,3539,E5139W1FJ3,X88YLZX0JX,7KGJ3C5TSW,648S19YUFF,BYU3R2LQF8,GOWRW4JCE7,S0E37H52ON,PG8MOC0UZI,LJ6H5XBD2A,NaT,A1W2TVMK1S
4162,4165,Mathew,Clark,1991-11-20,"Richardson, Rogers and Carter",frosteleanor@hill.biz,Flat 0\nCook coves\nPort Eleanor\nS1H 0FS,United Kingdom,GB,+44191 496 0673,NaT,aaa706b9-978e-4c21-995e-c3643e4aad37
4357,4360,Sarah,Hughes,1955-03-25,Evans LLC,helenjones@howe.info,Studio 8\nPaige corners\nGrahamborough\nEX8A 3XY,United Kingdom,GB,(0118) 496 0393,NaT,e0ef9b2f-18aa-4a95-8edf-2940b1fad427
4984,4987,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
5306,5309,XKDVQD7BH2,4YSEX8AY1Z,RQTF5XSXP4,GKJZ58DTHT,789HWCYC7M,KJW5WR7W16,XN9NGL5C0B,NTCGYW8LVC,MUXPJD0BZY,NaT,LNRNI6X6VL
5307,5310,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
5553,5557,Roy,Grein Groth,1940-05-25,Hering Stiftung & Co. KG,frederik62@etzold.de,Aribert-Berger-Platz 8/8\n97343 Olpe,Germany,DE,06149607023,NaT,5abba93d-d9b3-40d0-851b-679ff1c44f1c
6134,6138,Brit,Köster,1984-04-03,Rosenow,bschueler@pergande.net,Scheelstr. 56\n12848 Jena,Germany,DE,(08408) 908058,NaT,8f9ba56a-e467-4517-b882-a282c0c4d2b2
6300,6305,Gareth,Davis,1967-12-22,Williams-French,grayolivia@barber-thompson.co.uk,Flat 41\nKing bridge\nLake Marcshire\nEC2 5AR,United Kingdom,GB,(0808) 157 0190,NaT,2da1c8e3-4881-420a-9a79-04b996f98f45
6420,6426,EI10BU4INS,SH6Y92V6IK,D2OZZHWOLK,LNFBRXXUT4,TFEA83AAHP,XGYW43ZF8B,50KUU3PQUF,FB13AKRI21,GA2YQ189FL,NaT,23WTQ63AET
6488,6494,Siegmund,Tschentscher,1973-12-03,Kranz,nancy55@ullmann.de,Geißlergasse 927\n03944 Northeim,Germany,DE,+49(0)9721 211397,NaT,db2fc02b-7e8e-4d87-9caa-cd577f517c7f
6920,6927,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
7737,7747,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
8386,8398,I7IJDAPMIM,LUNRZWUKRB,QTVEU5TR8H,JXKOHA5B8F,JK2J6N4DLG,FW3EMRJ25W,EWE3U0DZIV,OS2P9CMHR6,G2D0EI6DT3,NaT,8FB8XB78NQ
8942,8955,Ross,Morgan,1982-07-27,Payne Group,foxbeth@walker.net,Flat 54\nNorman parks\nRobinsontown\nE1 9JD,United Kingdom,GB,(0306)9990937,NaT,5048db03-16cb-48ca-bda5-2b503c422167
9013,9026,TG6PAO2RAB,PIG6VAZUPM,L3E8OV4UAC,ROL0IMK6UH,EIV7XWUJ8I,KHJLOAKCW2,GMRBOMI0O1,5D74J6FPFJ,65I9CX7VF2,NaT,HEGG0N3ICG
9022,9035,Damian,Murphy,1992-09-09,"Harris, North and Day",reidmegan@matthews.com,65 Diane roads\nJohnsonhaven\nM95 9YZ,United Kingdom,GB,+44(0)1914960102,NaT,4ffd8820-9f66-432c-ad49-a0bd1ca8c41e
9355,9368,Marilyn,Whittaker,1971-03-21,Jones Inc,walkerandrea@anderson-dale.com,Studio 97y\nTurnbull stravenue\nGeorgeport\nOL...,United Kingdom,GB,+44(0)2074960344,NaT,f2725bff-dd02-45ca-a2f4-173c9e26e437
10013,10025,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
10211,10224,VCQL3ML6ZT,HULT86HONJ,TLSTUEIKI0,QSS0MWBGFZ,1WNILGM5MK,R4HMRLEIXV,YOTSVPRBQ7,LZGTB0T5Z7,6VGTZ6ANEA,NaT,AKXDQ62K1V
10224,10237,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
10360,10373,G1SI2RM0KA,67VJEE6DS2,YTC82GP4XE,M4Z6M30SJ3,U1AZKY6URZ,N9D1AYQOJ0,5EFAFD0JLI,IM8MN1L9MJ,Y0AKRC4TUP,NaT,7JTCX4UVLK
10668,10682,Keith,Larson,1943-07-16,Reeves LLC,michael81@smith.com,"85161 Billy Court Suite 152\nNorth Elizabeth, ...",United States,US,797.163.7892x104,NaT,42246bc3-ea43-4baa-bb47-df2a07fe88fa
10988,11002,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
11361,11376,Peter,Sims,1958-01-17,Parker-Bull,williamsashleigh@edwards.com,Studio 42w\nLinda valleys\nNorth Jake\nL9T 7NY,United Kingdom,GB,+44121 496 0697,NaT,ff8309cc-09ab-4726-ac3e-de7b55239885
11366,11381,31XQ1Z35J9,8LR57D7RZ0,O1LIA1MT1N,66V9WU2HU1,XASHXWHN80,NZDOEJPB2M,PNRMPSYR1J,RVRFD92E48,CLGG66L3JK,NaT,C7N3K5VF9U
11443,11459,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
11598,11615,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
11761,11778,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
11864,11881,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
12092,12110,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
12145,12163,Lisa,Brooks,1951-11-09,"Woods, Clarke and Turner",vhall@smith.info,87 Shaw pines\nWest Joshhaven\nTD8 9HF,United Kingdom,GB,01632 960 718,NaT,c313c32f-aeac-4077-9008-9a3adb12f616
12177,12197,2GU3G97VI1,91RL47Q2WC,RQI3KQXFBQ,D4KULDKYME,YM2YGPR8W1,4M2VPXJHBE,RQRB7RMTAD,XKI9UXSCZ1,35OGAP18JU,NaT,YIBFXQLD4A
12584,12606,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
12689,12711,Kuno,Döring,2001-10-20,Gerlach AG,rosalindemitschke@pechel.de,Klappstr. 08\n79928 Gifhorn,Germany,DE,0140420696,NaT,f2fde7dc-f7fb-47f5-9429-0c837114fdf6
12737,12759,Violetta,Junk,2001-09-19,Rust,adalbertbriemer@conradi.de,Ursel-Briemer-Platz 33\n39351 Schrobenhausen,Germany,DE,(00833) 22932,NaT,b66b62d3-7ee7-4e6d-a958-7984d9ab1cfb
13111,13135,F3LGJ1NZ0I,IXWSZZ2VPN,1IA43NTJFB,9WSM9X17XK,M5ZDMLPP45,W5VT0DOEKO,3518UD5CE8,QREF9WLI2A,EIP7YUL5CE,NaT,55II6WK8D2
13855,13879,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NaT,NULL
14101,14124,DD0K0FUDRY,Q9U9JNG44F,M7HZECVQVC,DJXWS4B52O,X29OBIYMTI,8EK3ZFIGXL,7ZNO5EBALT,XPVCZE2L8B,XBL6JO9DU6,NaT,1YOGCW4V46
14311,14335,Geoffrey,Wilkinson,1981-11-29,"Smith, Curtis and Wright",mauricecooper@smith.info,Studio 4\nCharlie vista\nBrookeshaven\nL2 9SW,United Kingdom,GB,+44191 496 0941,NaT,1e2e9d43-6197-415b-ba8a-d4a5024777d3
14490,14514,Rachel,Hicks,1993-03-29,Tyler Group,samantha45@barton.net,33 Carter hill\nJonesmouth\nIM1 5YG,United Kingdom,GB,+44(0)8081570526,NaT,eb241c22-081d-412e-bf42-e22b3b095b37
14499,14523,YWM71XYN17,PYC56FDP4V,6WAQ2SVK0Q,WGP4NBYFT6,6VIJ9KJU8P,NI3KEEZPTY,T4WBZSW0XI,44YAIDY048,QVAV1H2QVH,NaT,7PYPXC0PPN

In [21]:
a = users_rd.iloc[752]
a

index                   752
first_name       PYCLKLLC7I
last_name        W350SCUD6R
date_of_birth    KBTI7FI7Y3
company          R7IZUNSQX0
email_address    3Q791B3VIY
address          YW2YXLOQ5J
country          I7G4DMDZOZ
country_code     VSM4IZ4EL3
phone_number     A4Q4HQBI3I
join_date               NaT
user_uuid        W43MSCMQ88
Name: 752, dtype: object

In [22]:
b = users_rd.iloc[751]
b

index                                                          751
first_name                                                Terrence
last_name                                                    Moyer
date_of_birth                                           1999-08-21
company                                                Douglas LLC
email_address                            hmartin@campbell-horn.com
address          9516 Martinez Parkways Suite 850\nWest Victor,...
country                                              United States
country_code                                                    US
phone_number                                      076.583.0124x510
join_date                                               2019-07-19
user_uuid                     9c9412e3-78c0-47c0-83f2-635414a2230a
Name: 751, dtype: object

In [23]:
users_rd.replace('NULL', np.nan, inplace=True)

In [24]:
users_rd.dropna(subset=['date_of_birth', 'email_address', 'user_uuid'], how='any', axis=0, inplace=True)

In [25]:
# Check for any NaT (Not a Time) values in the column
nan_entries = users_rd[users_rd['join_date'].isna()]

print(f"Number of NaT/NaN entries: {len(nan_entries)}")
display(nan_entries)

Number of NaT/NaN entries: 38

,index,first_name,last_name,date_of_birth,company,email_address,address,country,country_code,phone_number,join_date,user_uuid
202,202,Mohamed,Woodward,1968-10-25,"Barrett, Jones and Smith",colemandanny@grant-lamb.org,96 Danny trail\nEast Valerie\nKA39 2JN,United Kingdom,GB,(0113)4960884,NaT,6904f151-6d32-4d1e-b477-41801a9a8e83
752,752,PYCLKLLC7I,W350SCUD6R,KBTI7FI7Y3,R7IZUNSQX0,3Q791B3VIY,YW2YXLOQ5J,I7G4DMDZOZ,VSM4IZ4EL3,A4Q4HQBI3I,NaT,W43MSCMQ88
1046,1047,GI4C78KWH0,UTB5PPYFG8,OFH8YGZJWN,CA1XGS8GZW,7HSZB429UK,63GXGYR3XL,AJ1ENKS3QL,QVUW9JSKY3,64ZO0ONUQO,NaT,BUE34OU973
1073,1074,Michelle,Young,1963-08-10,"Jones, Simpson and Bates",victoriahughes@lee-hooper.com,757 Ahmed ford\nEast Bethmouth\nM3 7XJ,United Kingdom,GB,+44(0)1632 960 310,NaT,4f3703c0-e020-4d36-93f2-38f077e8467e
1347,1349,Jonathan,Johnson,1952-12-03,"Hall, Thomson and Stevens",adamshugh@evans-gough.com,1 Reece plains\nWest Jayhaven\nN2 5JH,United Kingdom,GB,020 7946 0952,NaT,7508866e-18dd-4530-890b-a7fda09595f0
1569,1571,Mandy,Little,1990-07-23,Jackson and Sons,jamieglover@ingram.com,96 Knowles ports\nVincentfurt\nNP0P 0NB,United Kingdom,GB,0117 4960172,NaT,74a4e9bf-4baf-4f17-bd35-594471d68938
2439,2441,Johannes,Mitschke,2003-06-04,Huhn,apollonia19@hering.net,Klaus-D.-Hellwig-Gasse 118\n13930 Jessen,Germany,DE,+49(0)0887 099768,NaT,a9073341-1fa3-4bcc-982f-5287f4224485
2480,2482,Ashley,Kelly,1941-11-27,James-Marshall,ymorris@buckley.info,Flat 7\nLuke falls\nSouth Brucemouth\nSM4V 9FS,United Kingdom,GB,+44(0)114 496 0729,NaT,a307bb45-6762-4766-a591-f14545f3a9e2
2995,2997,DPAJNJL6PR,B8ZGN8ZJ84,PQPEUO937L,0YJ2FRMDB4,O5Q6D7FDAF,Y1GY1G3EM5,XGI7FM0VBJ,0CU6LW3NKB,DU9UJ42F3E,NaT,56URKLG01W
3164,3167,Barbara,Daniels,1960-10-30,Kemp Inc,zcole@gill.com,Studio 54\nChloe brook\nWestonshire\nOX9X 9PY,United Kingdom,GB,+44(0)115 496 0250,NaT,d2471fcd-4aae-438f-b0ef-6de2a68ac3ab
3536,3539,E5139W1FJ3,X88YLZX0JX,7KGJ3C5TSW,648S19YUFF,BYU3R2LQF8,GOWRW4JCE7,S0E37H52ON,PG8MOC0UZI,LJ6H5XBD2A,NaT,A1W2TVMK1S
4162,4165,Mathew,Clark,1991-11-20,"Richardson, Rogers and Carter",frosteleanor@hill.biz,Flat 0\nCook coves\nPort Eleanor\nS1H 0FS,United Kingdom,GB,+44191 496 0673,NaT,aaa706b9-978e-4c21-995e-c3643e4aad37
4357,4360,Sarah,Hughes,1955-03-25,Evans LLC,helenjones@howe.info,Studio 8\nPaige corners\nGrahamborough\nEX8A 3XY,United Kingdom,GB,(0118) 496 0393,NaT,e0ef9b2f-18aa-4a95-8edf-2940b1fad427
5306,5309,XKDVQD7BH2,4YSEX8AY1Z,RQTF5XSXP4,GKJZ58DTHT,789HWCYC7M,KJW5WR7W16,XN9NGL5C0B,NTCGYW8LVC,MUXPJD0BZY,NaT,LNRNI6X6VL
5553,5557,Roy,Grein Groth,1940-05-25,Hering Stiftung & Co. KG,frederik62@etzold.de,Aribert-Berger-Platz 8/8\n97343 Olpe,Germany,DE,06149607023,NaT,5abba93d-d9b3-40d0-851b-679ff1c44f1c
6134,6138,Brit,Köster,1984-04-03,Rosenow,bschueler@pergande.net,Scheelstr. 56\n12848 Jena,Germany,DE,(08408) 908058,NaT,8f9ba56a-e467-4517-b882-a282c0c4d2b2
6300,6305,Gareth,Davis,1967-12-22,Williams-French,grayolivia@barber-thompson.co.uk,Flat 41\nKing bridge\nLake Marcshire\nEC2 5AR,United Kingdom,GB,(0808) 157 0190,NaT,2da1c8e3-4881-420a-9a79-04b996f98f45
6420,6426,EI10BU4INS,SH6Y92V6IK,D2OZZHWOLK,LNFBRXXUT4,TFEA83AAHP,XGYW43ZF8B,50KUU3PQUF,FB13AKRI21,GA2YQ189FL,NaT,23WTQ63AET
6488,6494,Siegmund,Tschentscher,1973-12-03,Kranz,nancy55@ullmann.de,Geißlergasse 927\n03944 Northeim,Germany,DE,+49(0)9721 211397,NaT,db2fc02b-7e8e-4d87-9caa-cd577f517c7f
8386,8398,I7IJDAPMIM,LUNRZWUKRB,QTVEU5TR8H,JXKOHA5B8F,JK2J6N4DLG,FW3EMRJ25W,EWE3U0DZIV,OS2P9CMHR6,G2D0EI6DT3,NaT,8FB8XB78NQ
8942,8955,Ross,Morgan,1982-07-27,Payne Group,foxbeth@walker.net,Flat 54\nNorman parks\nRobinsontown\nE1 9JD,United Kingdom,GB,(0306)9990937,NaT,5048db03-16cb-48ca-bda5-2b503c422167
9013,9026,TG6PAO2RAB,PIG6VAZUPM,L3E8OV4UAC,ROL0IMK6UH,EIV7XWUJ8I,KHJLOAKCW2,GMRBOMI0O1,5D74J6FPFJ,65I9CX7VF2,NaT,HEGG0N3ICG
9022,9035,Damian,Murphy,1992-09-09,"Harris, North and Day",reidmegan@matthews.com,65 Diane roads\nJohnsonhaven\nM95 9YZ,United Kingdom,GB,+44(0)1914960102,NaT,4ffd8820-9f66-432c-ad49-a0bd1ca8c41e
9355,9368,Marilyn,Whittaker,1971-03-21,Jones Inc,walkerandrea@anderson-dale.com,Studio 97y\nTurnbull stravenue\nGeorgeport\nOL...,United Kingdom,GB,+44(0)2074960344,NaT,f2725bff-dd02-45ca-a2f4-173c9e26e437
10211,10224,VCQL3ML6ZT,HULT86HONJ,TLSTUEIKI0,QSS0MWBGFZ,1WNILGM5MK,R4HMRLEIXV,YOTSVPRBQ7,LZGTB0T5Z7,6VGTZ6ANEA,NaT,AKXDQ62K1V
10360,10373,G1SI2RM0KA,67VJEE6DS2,YTC82GP4XE,M4Z6M30SJ3,U1AZKY6URZ,N9D1AYQOJ0,5EFAFD0JLI,IM8MN1L9MJ,Y0AKRC4TUP,NaT,7JTCX4UVLK
10668,10682,Keith,Larson,1943-07-16,Reeves LLC,michael81@smith.com,"85161 Billy Court Suite 152\nNorth Elizabeth, ...",United States,US,797.163.7892x104,NaT,42246bc3-ea43-4baa-bb47-df2a07fe88fa
11361,11376,Peter,Sims,1958-01-17,Parker-Bull,williamsashleigh@edwards.com,Studio 42w\nLinda valleys\nNorth Jake\nL9T 7NY,United Kingdom,GB,+44121 496 0697,NaT,ff8309cc-09ab-4726-ac3e-de7b55239885
11366,11381,31XQ1Z35J9,8LR57D7RZ0,O1LIA1MT1N,66V9WU2HU1,XASHXWHN80,NZDOEJPB2M,PNRMPSYR1J,RVRFD92E48,CLGG66L3JK,NaT,C7N3K5VF9U
12145,12163,Lisa,Brooks,1951-11-09,"Woods, Clarke and Turner",vhall@smith.info,87 Shaw pines\nWest Joshhaven\nTD8 9HF,United Kingdom,GB,01632 960 718,NaT,c313c32f-aeac-4077-9008-9a3adb12f616
12177,12197,2GU3G97VI1,91RL47Q2WC,RQI3KQXFBQ,D4KULDKYME,YM2YGPR8W1,4M2VPXJHBE,RQRB7RMTAD,XKI9UXSCZ1,35OGAP18JU,NaT,YIBFXQLD4A
12689,12711,Kuno,Döring,2001-10-20,Gerlach AG,rosalindemitschke@pechel.de,Klappstr. 08\n79928 Gifhorn,Germany,DE,0140420696,NaT,f2fde7dc-f7fb-47f5-9429-0c837114fdf6
12737,12759,Violetta,Junk,2001-09-19,Rust,adalbertbriemer@conradi.de,Ursel-Briemer-Platz 33\n39351 Schrobenhausen,Germany,DE,(00833) 22932,NaT,b66b62d3-7ee7-4e6d-a958-7984d9ab1cfb
13111,13135,F3LGJ1NZ0I,IXWSZZ2VPN,1IA43NTJFB,9WSM9X17XK,M5ZDMLPP45,W5VT0DOEKO,3518UD5CE8,QREF9WLI2A,EIP7YUL5CE,NaT,55II6WK8D2
14101,14124,DD0K0FUDRY,Q9U9JNG44F,M7HZECVQVC,DJXWS4B52O,X29OBIYMTI,8EK3ZFIGXL,7ZNO5EBALT,XPVCZE2L8B,XBL6JO9DU6,NaT,1YOGCW4V46
14311,14335,Geoffrey,Wilkinson,1981-11-29,"Smith, Curtis and Wright",mauricecooper@smith.info,Studio 4\nCharlie vista\nBrookeshaven\nL2 9SW,United Kingdom,GB,+44191 496 0941,NaT,1e2e9d43-6197-415b-ba8a-d4a5024777d3
14490,14514,Rachel,Hicks,1993-03-29,Tyler Group,samantha45@barton.net,33 Carter hill\nJonesmouth\nIM1 5YG,United Kingdom,GB,+44(0)8081570526,NaT,eb241c22-081d-412e-bf42-e22b3b095b37
14499,14523,YWM71XYN17,PYC56FDP4V,6WAQ2SVK0Q,WGP4NBYFT6,6VIJ9KJU8P,NI3KEEZPTY,T4WBZSW0XI,44YAIDY048,QVAV1H2QVH,NaT,7PYPXC0PPN

In [26]:
users_rd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15299 entries, 0 to 15319
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          15299 non-null  int64
 1   first_name     15299 non-null  object
 2   last_name      15299 non-null  object
 3   date_of_birth  15299 non-null  object
 4   company        15299 non-null  object
 5   email_address  15299 non-null  object
 6   address        15299 non-null  object
 7   country        15299 non-null  object
 8   country_code   15299 non-null  object
 9   phone_number   15299 non-null  object
 10  join_date      15261 non-null  object
 11  user_uuid      15299 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.5+ MB

In [30]:
import tabula as tb
link = "card_details.pdf"
pdf_data = tb.read_pdf(link, pages='all')
pdf_data = pd.concat(pdf_data, ignore_index=True)
pdf_data = pdf_data.dropna(axis=1, how = 'all')
pdf_df = pdf_data.reset_index(drop=True)
print(pdf_df.head())

        card_number expiry_date                card_provider  \
0    30060773296197       09/26  Diners Club / Carte Blanche
1   349624180933183       10/23             American Express
2  3529023891650490       06/23                 JCB 16 digit
3   213142929492281       09/27                 JCB 15 digit
4      502067329974       10/25                      Maestro

  date_payment_confirmed
0             2015-11-25
1             2001-06-18
2             2000-12-26
3             2011-02-12
4             1997-03-13

In [32]:
import tabula as tb
import pandas as pd

# Read the PDF with parameters that might help
link = "card_details.pdf"
pdf_data = tb.read_pdf(link, pages='all', multiple_tables=True, lattice=True)

# If pdf_data is a list of DataFrames, concatenate them
if isinstance(pdf_data, list):
    pdf_data = pd.concat(pdf_data, ignore_index=True)

# Display the raw DataFrame to understand its structure
print(pdf_data.head())

# Optionally clean up unwanted characters
pdf_data = pdf_data.replace({'\\': ''}, regex=True)

# Assume the structure is: card_number, expiry_date, card_provider, and date_payment_confirmed
# Handle cases where 'date_payment_confirmed' appears on a new line

# This assumes that 'date_payment_confirmed' is only in the last row of a misaligned entry
# Rebuild DataFrame from potentially misaligned entries
fixed_data = []

# Iterate through rows to fix alignment
for i in range(0, len(pdf_data), 1):
    row = pdf_data.iloc[i]
    if pd.isna(row['date_payment_confirmed']):
        # Append to the current row if date_payment_confirmed is missing
        if fixed_data:
            fixed_data[-1]['date_payment_confirmed'] = row['card_provider']
        fixed_data.append(row.to_dict())
    else:
        fixed_data.append(row.to_dict())

# Convert list of dicts to DataFrame
fixed_df = pd.DataFrame(fixed_data)

# Drop columns that are entirely NaN
fixed_df = fixed_df.dropna(axis=1, how='all')

# Reset index to clean up DataFrame
fixed_df = fixed_df.reset_index(drop=True)

# Display the cleaned DataFrame
print(fixed_df.head())

        card_number expiry_date                card_provider  \
0    30060773296197       09/26  Diners Club / Carte Blanche
1   349624180933183       10/23             American Express
2  3529023891650490       06/23                 JCB 16 digit
3   213142929492281       09/27                 JCB 15 digit
4      502067329974       10/25                      Maestro

  date_payment_confirmed
0             2015-11-25
1             2001-06-18
2             2000-12-26
3             2011-02-12
4             1997-03-13

error: bad escape (end of pattern) at position 0